import type { Sector, DigitalService, DigitalServiceType } from "@/types/sectors"

export const digitalServicesData: Record<DigitalServiceType, DigitalService> = {
  site_web: {
    type: "site_web",
    title: "Site Web Professionnel",
    description: "Un site web moderne, responsive et optimisé pour convertir vos visiteurs en clients.",
    benefits: ["Design sur mesure", "Optimisé mobile", "Chargement rapide", "SEO intégré"],
  },
  seo_local: {
    type: "seo_local",
    title: "Référencement Local",
    description: "Apparaissez en premier sur Google pour les recherches locales de votre secteur.",
    benefits: ["Google My Business optimisé", "Citations locales", "Mots-clés géolocalisés", "Fiche établissement"],
  },
  google_ads: {
    type: "google_ads",
    title: "Google Ads",
    description: "Campagnes publicitaires ciblées pour générer des leads qualifiés immédiatement.",
    benefits: ["Résultats immédiats", "Ciblage précis", "Budget maîtrisé", "ROI mesurable"],
  },
  facebook_ads: {
    type: "facebook_ads",
    title: "Facebook & Instagram Ads",
    description: "Publicités sur les réseaux sociaux pour toucher votre audience idéale.",
    benefits: ["Ciblage démographique", "Visuels engageants", "Retargeting", "Notoriété locale"],
  },
  avis_google: {
    type: "avis_google",
    title: "Gestion des Avis Google",
    description: "Stratégie pour collecter plus d'avis positifs et gérer votre e-réputation.",
    benefits: ["Collecte automatisée", "Réponses aux avis", "Amélioration note moyenne", "QR codes en point de vente"],
  },
  crm: {
    type: "crm",
    title: "CRM & Application Métier",
    description: "Solution CRM sur mesure pour gérer vos clients, prospects et processus métier. Interface intuitive adaptée à votre activité.",
    benefits: ["CRM personnalisé", "Tableaux de bord métier", "Gestion pipeline", "App mobile incluse", "Automatisations"],
  },
  emailing: {
    type: "emailing",
    title: "Email Marketing",
    description: "Newsletters et séquences d'emails pour fidéliser et convertir vos contacts.",
    benefits: ["Newsletters automatisées", "Séquences de bienvenue", "Promotions ciblées", "Statistiques détaillées"],
  },
  automation: {
    type: "automation",
    title: "Automatisation Marketing",
    description: "Automatisez vos tâches répétitives pour gagner du temps et ne rien oublier.",
    benefits: ["Workflows automatiques", "Relances automatiques", "Notifications SMS", "Gain de temps"],
  },
  chatbot: {
    type: "chatbot",
    title: "Chatbot & Assistant IA",
    description: "Un assistant virtuel disponible 24/7 pour répondre aux questions de vos visiteurs.",
    benefits: ["Disponible 24/7", "Répond aux FAQ", "Qualifie les leads", "Prise de RDV automatique"],
  },
  reseaux_sociaux: {
    type: "reseaux_sociaux",
    title: "Gestion Réseaux Sociaux",
    description: "Animation de vos comptes pour développer votre communauté et votre notoriété.",
    benefits: ["Planning éditorial", "Création de contenu", "Interaction communauté", "Reporting mensuel"],
  },
  reservation: {
    type: "reservation",
    title: "Système de Réservation",
    description: "Permettez à vos clients de réserver en ligne 24h/24 sans intervention.",
    benefits: ["Réservation 24/7", "Rappels automatiques", "Synchronisation agenda", "Paiement en ligne"],
  },
  ecommerce: {
    type: "ecommerce",
    title: "Boutique E-commerce",
    description: "Vendez vos produits en ligne avec une boutique complète et sécurisée.",
    benefits: ["Paiement sécurisé", "Gestion stocks", "Livraison intégrée", "Click & Collect"],
  },
  analytics: {
    type: "analytics",
    title: "Analytics & Tableaux de Bord",
    description: "Suivez vos performances avec des rapports clairs et des KPIs pertinents.",
    benefits: ["Rapports automatisés", "KPIs métier", "Suivi conversions", "Décisions éclairées"],
  },
  app_mobile: {
    type: "app_mobile",
    title: "Application Mobile",
    description: "Application iOS et Android sur mesure pour vos clients ou votre équipe. Expérience native optimisée.",
    benefits: ["iOS & Android", "Notifications push", "Mode hors-ligne", "Mises à jour faciles", "Publication stores"],
  },
}

export function get_digital_service(type: DigitalServiceType): DigitalService {
  return digitalServicesData[type]
}

export function get_sector_digital_services(sector: Sector): DigitalService[] {
  return sector.digitalServices.map((type) => digitalServicesData[type])
}
export const sectors: Sector[] = [
  // ============================================
  // COMMERCE & RETAIL
  // ============================================
  {
    slug: "restaurant",
    name: "Restaurant",
    namePlural: "Restaurants",
    icon: "UtensilsCrossed",
    category: "commerce",
    metaTitle: "Création Site Web Restaurant | Menu en ligne & Réservation",
    metaDescription: "Créez un site web professionnel pour votre restaurant. Menu digital, réservation en ligne, Click & Collect. Augmentez vos réservations de 40%.",
    headline: "Un site web qui met l'eau à la bouche",
    subheadline: "Attirez plus de clients avec un site élégant présentant votre carte, vos horaires et permettant la réservation en ligne.",
    painPoints: [
      "Difficile d'attirer de nouveaux clients sans présence en ligne",
      "Les clients appellent pour des informations basiques (horaires, menu)",
      "Pas de système de réservation automatisé",
      "Menu papier difficile à mettre à jour",
    ],
    solutions: [
      { title: "Menu digital interactif", description: "Présentez vos plats avec photos et descriptions appétissantes, mise à jour instantanée" },
      { title: "Réservation en ligne 24/7", description: "Vos clients réservent quand ils veulent, vous réduisez les appels téléphoniques" },
      { title: "Click & Collect intégré", description: "Commande en ligne pour retrait sur place, augmentez votre chiffre d'affaires" },
      { title: "Avis Google intégrés", description: "Affichez vos meilleures critiques pour rassurer les nouveaux clients" },
    ],
    specificFeatures: ["Menu QR Code", "Galerie photos", "Carte interactive", "Intégration réseaux sociaux", "Blog recettes"],
    digitalServices: ["site_web", "seo_local", "avis_google", "reservation", "reseaux_sociaux", "emailing", "app_mobile", "crm"],
    stats: [
      { label: "Réservations en ligne", value: "+40%" },
      { label: "Appels réduits", value: "-60%" },
      { label: "Nouveaux clients", value: "+35%" },
    ],
    faqs: [
      { question: "Puis-je modifier mon menu moi-même ?", answer: "Oui, nous vous fournissons un back-office simple pour mettre à jour votre carte, vos prix et vos photos en quelques clics." },
      { question: "Le système de réservation est-il payant ?", answer: "Non, la réservation est intégrée sans frais supplémentaires. Vous recevez les demandes par email et SMS." },
      { question: "Combien de temps pour créer mon site ?", answer: "Un site restaurant est généralement livré en 2-3 semaines après validation du contenu." },
    ],
  },
  {
    slug: "boulangerie-patisserie",
    name: "Boulangerie-Pâtisserie",
    namePlural: "Boulangeries-Pâtisseries",
    icon: "Croissant",
    category: "commerce",
    metaTitle: "Site Web Boulangerie Pâtisserie | Commande en ligne",
    metaDescription: "Site internet pour boulangerie et pâtisserie. Présentez vos créations, activez la commande en ligne. Solution clé en main.",
    headline: "Votre vitrine gourmande sur le web",
    subheadline: "Mettez en valeur vos créations artisanales et permettez à vos clients de commander leurs pains et gâteaux en ligne.",
    painPoints: [
      "Les clients ne connaissent pas toute votre gamme de produits",
      "Commandes de gâteaux par téléphone chronophages",
      "Pas de visibilité sur vos horaires d'ouverture en ligne",
      "Difficulté à communiquer sur vos spécialités",
    ],
    solutions: [
      { title: "Catalogue produits visuel", description: "Photos haute qualité de vos pains, viennoiseries et pâtisseries" },
      { title: "Commande de gâteaux en ligne", description: "Vos clients commandent leur gâteau d'anniversaire directement sur le site" },
      { title: "Horaires et actualités", description: "Informez sur vos fermetures, nouveautés saisonnières" },
      { title: "Programme fidélité", description: "Fidélisez votre clientèle avec un système de points" },
    ],
    specificFeatures: ["Galerie créations", "Formulaire commande spéciale", "Actualités saisonnières", "Carte de la boutique"],
    digitalServices: ["site_web", "seo_local", "avis_google", "reseaux_sociaux", "emailing", "ecommerce", "app_mobile", "crm"],
    stats: [
      { label: "Commandes spéciales", value: "+50%" },
      { label: "Visibilité locale", value: "+70%" },
      { label: "Fidélisation", value: "+25%" },
    ],
    faqs: [
      { question: "Puis-je vendre directement en ligne ?", answer: "Oui, nous pouvons intégrer un système de paiement pour la vente de bons cadeaux ou de commandes spéciales." },
      { question: "Comment gérer les commandes ?", answer: "Vous recevez les commandes par email avec tous les détails (date, produit, message personnalisé)." },
    ],
  },
  {
    slug: "fleuriste",
    name: "Fleuriste",
    namePlural: "Fleuristes",
    icon: "Flower2",
    category: "commerce",
    metaTitle: "Création Site Web Fleuriste | Boutique en ligne fleurs",
    metaDescription: "Site e-commerce pour fleuriste. Vente en ligne, livraison de bouquets. Augmentez vos ventes avec une boutique florale élégante.",
    headline: "Faites fleurir votre business en ligne",
    subheadline: "Une boutique en ligne élégante pour vendre vos créations florales et proposer la livraison à domicile.",
    painPoints: [
      "Concurrence des grandes enseignes en ligne",
      "Clients qui ne connaissent pas vos créations",
      "Gestion des commandes de dernière minute",
      "Pas de livraison proposée",
    ],
    solutions: [
      { title: "Boutique en ligne complète", description: "Vendez vos bouquets, plantes et accessoires 24h/24" },
      { title: "Livraison intégrée", description: "Définissez vos zones de livraison et créneaux disponibles" },
      { title: "Occasions spéciales", description: "Pages dédiées Saint-Valentin, Fête des mères, deuil..." },
      { title: "Abonnements floraux", description: "Proposez des formules d'abonnement récurrentes" },
    ],
    specificFeatures: ["Paiement sécurisé", "Calendrier de livraison", "Messages personnalisés", "Galerie créations"],
    digitalServices: ["site_web", "seo_local", "ecommerce", "avis_google", "reseaux_sociaux", "facebook_ads", "emailing"],
    stats: [
      { label: "Ventes en ligne", value: "+60%" },
      { label: "Panier moyen", value: "+25%" },
      { label: "Zone de chalandise", value: "x3" },
    ],
    faqs: [
      { question: "Comment gérer les stocks ?", answer: "Le site peut être connecté à votre gestion de stock ou vous pouvez désactiver les produits indisponibles manuellement." },
      { question: "Les frais de livraison sont-ils paramétrables ?", answer: "Oui, vous définissez vos zones et tarifs de livraison selon la distance." },
    ],
  },
  {
    slug: "boutique-vetements",
    name: "Boutique de Vêtements",
    namePlural: "Boutiques de Vêtements",
    icon: "Shirt",
    category: "commerce",
    metaTitle: "Site E-commerce Mode | Boutique Vêtements en ligne",
    metaDescription: "Créez votre boutique de vêtements en ligne. E-commerce mode avec gestion des tailles, couleurs et stocks. Solution complète.",
    headline: "Votre boutique mode ouverte 24h/24",
    subheadline: "Un e-commerce élégant pour vendre vos collections en ligne et toucher une clientèle nationale.",
    painPoints: [
      "Ventes limitées aux heures d'ouverture",
      "Clientèle uniquement locale",
      "Gestion des tailles et couleurs complexe",
      "Stocks difficiles à suivre",
    ],
    solutions: [
      { title: "E-commerce complet", description: "Gestion des variantes (tailles, couleurs), paiement sécurisé" },
      { title: "Lookbook digital", description: "Présentez vos collections avec des visuels inspirants" },
      { title: "Gestion des retours", description: "Processus de retour simple pour rassurer vos clients" },
      { title: "Newsletter mode", description: "Informez vos clients des nouvelles collections" },
    ],
    specificFeatures: ["Guide des tailles", "Wishlist", "Avis clients", "Cross-selling", "Instagram shopping"],
    digitalServices: ["site_web", "ecommerce", "facebook_ads", "google_ads", "reseaux_sociaux", "emailing", "crm", "analytics", "app_mobile"],
    stats: [
      { label: "Chiffre d'affaires", value: "+80%" },
      { label: "Clients hors zone", value: "+45%" },
      { label: "Panier moyen", value: "+30%" },
    ],
    faqs: [
      { question: "Quelle plateforme utilisez-vous ?", answer: "Nous développons sur mesure ou utilisons Shopify selon vos besoins et budget." },
      { question: "Comment gérer les retours ?", answer: "Un espace client permet de générer des étiquettes retour et suivre les remboursements." },
    ],
  },
  {
    slug: "bijouterie",
    name: "Bijouterie",
    namePlural: "Bijouteries",
    icon: "Gem",
    category: "commerce",
    metaTitle: "Site Web Bijouterie | Vente Bijoux en ligne",
    metaDescription: "Site e-commerce bijouterie joaillerie. Présentez vos créations avec élégance, vendez en ligne. Solution haut de gamme.",
    headline: "L'écrin digital de vos créations",
    subheadline: "Un site raffiné qui met en valeur vos bijoux et inspire confiance pour l'achat en ligne.",
    painPoints: [
      "Produits nécessitant une présentation haut de gamme",
      "Clients hésitants à acheter des bijoux en ligne",
      "Besoin de mettre en avant le savoir-faire",
      "Personnalisation des bijoux à gérer",
    ],
    solutions: [
      { title: "Visuels premium", description: "Photos zoomables, vidéos 360° de vos créations" },
      { title: "Certificats et garanties", description: "Affichez vos certifications pour rassurer" },
      { title: "Personnalisation en ligne", description: "Configurateur pour gravure et sur-mesure" },
      { title: "Paiement sécurisé", description: "3D Secure et options de paiement fractionné" },
    ],
    specificFeatures: ["Zoom haute définition", "Guide des tailles bagues", "Certificats téléchargeables", "Wishlist"],
    digitalServices: ["site_web", "ecommerce", "seo_local", "google_ads", "facebook_ads", "reseaux_sociaux", "emailing", "crm"],
    stats: [
      { label: "Conversion", value: "+35%" },
      { label: "Confiance client", value: "+50%" },
      { label: "Ventes gravure", value: "+40%" },
    ],
    faqs: [
      { question: "Comment rassurer les clients sur l'authenticité ?", answer: "Nous intégrons vos certificats, poinçons et garanties directement sur les fiches produits." },
      { question: "Le paiement en plusieurs fois est-il possible ?", answer: "Oui, nous intégrons des solutions comme Alma ou Klarna pour le paiement fractionné." },
    ],
  },

  // ============================================
  // SERVICES PROFESSIONNELS
  // ============================================
  {
    slug: "avocat",
    name: "Avocat",
    namePlural: "Avocats",
    icon: "Scale",
    category: "services",
    metaTitle: "Création Site Web Avocat | Cabinet Juridique",
    metaDescription: "Site internet professionnel pour avocat et cabinet juridique. Présentez vos domaines de compétence, générez des consultations.",
    headline: "Votre expertise juridique visible en ligne",
    subheadline: "Un site professionnel qui inspire confiance et génère des demandes de consultation qualifiées.",
    painPoints: [
      "Difficulté à se différencier de la concurrence",
      "Clients potentiels qui ne trouvent pas vos spécialités",
      "Temps perdu en appels pour des informations basiques",
      "Image digitale peu professionnelle",
    ],
    solutions: [
      { title: "Présentation des expertises", description: "Pages dédiées à chaque domaine du droit que vous pratiquez" },
      { title: "Prise de RDV en ligne", description: "Calendrier de consultation intégré type Calendly" },
      { title: "Blog juridique", description: "Publiez des articles pour démontrer votre expertise" },
      { title: "FAQ interactive", description: "Répondez aux questions fréquentes de vos clients" },
    ],
    specificFeatures: ["Formulaire de contact sécurisé", "Mentions déontologiques", "CV et parcours", "Tarifs indicatifs"],
    digitalServices: ["site_web", "seo_local", "google_ads", "avis_google", "reservation", "crm", "emailing"],
    stats: [
      { label: "Demandes de RDV", value: "+55%" },
      { label: "Visibilité Google", value: "+80%" },
      { label: "Appels qualifiés", value: "+40%" },
    ],
    faqs: [
      { question: "Le site respecte-t-il la déontologie ?", answer: "Oui, nous connaissons les règles du CNB et veillons à leur respect (mentions obligatoires, absence de publicité comparative, etc.)." },
      { question: "Puis-je publier des articles moi-même ?", answer: "Absolument, vous aurez accès à un CMS simple pour publier vos actualités juridiques." },
    ],
  },
  {
    slug: "expert-comptable",
    name: "Expert-Comptable",
    namePlural: "Experts-Comptables",
    icon: "Calculator",
    category: "services",
    metaTitle: "Site Web Expert-Comptable | Cabinet Comptable",
    metaDescription: "Création site internet cabinet comptable. Présentez vos services, attirez de nouveaux clients entreprises. Devis en ligne.",
    headline: "Digitalisez votre cabinet comptable",
    subheadline: "Un site moderne qui présente vos services et attire les entrepreneurs à la recherche d'un expert-comptable.",
    painPoints: [
      "Image vieillissante du cabinet",
      "Difficulté à attirer les jeunes entrepreneurs",
      "Services mal compris par les prospects",
      "Concurrence des solutions en ligne",
    ],
    solutions: [
      { title: "Présentation claire des services", description: "Comptabilité, fiscalité, social, juridique... tout est expliqué" },
      { title: "Simulateurs en ligne", description: "Calcul de charges, comparatif statuts juridiques" },
      { title: "Espace client sécurisé", description: "Échange de documents confidentiel" },
      { title: "Blog actualités", description: "Partagez les évolutions fiscales et sociales" },
    ],
    specificFeatures: ["Simulateur charges", "Devis en ligne", "Espace documentaire", "Témoignages clients"],
    digitalServices: ["site_web", "seo_local", "google_ads", "avis_google", "crm", "automation", "emailing", "chatbot"],
    stats: [
      { label: "Demandes de devis", value: "+65%" },
      { label: "Nouveaux clients", value: "+40%" },
      { label: "Image modernisée", value: "100%" },
    ],
    faqs: [
      { question: "Peut-on intégrer un espace client ?", answer: "Oui, nous pouvons créer un espace sécurisé pour l'échange de documents comptables avec vos clients." },
      { question: "Les simulateurs sont-ils personnalisables ?", answer: "Absolument, nous les adaptons à vos offres et barèmes spécifiques." },
    ],
  },
  {
    slug: "notaire",
    name: "Notaire",
    namePlural: "Notaires",
    icon: "FileSignature",
    category: "services",
    metaTitle: "Site Web Notaire | Étude Notariale",
    metaDescription: "Création site internet pour notaire et étude notariale. Présentez vos services, informez vos clients. Solution professionnelle.",
    headline: "Votre étude notariale à l'ère digitale",
    subheadline: "Un site institutionnel qui présente vos services et facilite la prise de contact avec votre étude.",
    painPoints: [
      "Clients mal informés sur les services notariaux",
      "Nombreux appels pour des renseignements basiques",
      "Image traditionnelle à moderniser",
      "Difficulté à expliquer les actes notariés",
    ],
    solutions: [
      { title: "Guide des actes notariés", description: "Expliquez clairement chaque type d'acte (immobilier, famille, entreprise)" },
      { title: "Prise de RDV en ligne", description: "Simplifiez la prise de rendez-vous pour vos clients" },
      { title: "Actualités juridiques", description: "Informez sur les évolutions législatives importantes" },
      { title: "Présentation de l'équipe", description: "Humanisez votre étude avec les portraits des collaborateurs" },
    ],
    specificFeatures: ["Calculateurs frais", "Documents à préparer", "FAQ détaillée", "Plan d'accès"],
    digitalServices: ["site_web", "seo_local", "reservation", "chatbot", "avis_google", "emailing"],
    stats: [
      { label: "Appels informatifs réduits", value: "-50%" },
      { label: "RDV en ligne", value: "+60%" },
      { label: "Satisfaction client", value: "+30%" },
    ],
    faqs: [
      { question: "Peut-on intégrer un simulateur de frais de notaire ?", answer: "Oui, nous intégrons des calculateurs pour les frais immobiliers, successions, etc." },
      { question: "Le site sera-t-il conforme à la réglementation ?", answer: "Absolument, nous respectons les obligations déontologiques de la profession." },
    ],
  },
  {
    slug: "agence-immobiliere",
    name: "Agence Immobilière",
    namePlural: "Agences Immobilières",
    icon: "Home",
    category: "services",
    metaTitle: "Site Web Agence Immobilière | Portail Annonces",
    metaDescription: "Création site internet agence immobilière. Portail d'annonces, estimation en ligne, génération de mandats. Solution complète.",
    headline: "Votre vitrine immobilière digitale",
    subheadline: "Un portail d'annonces performant pour présenter vos biens et générer des contacts acquéreurs et vendeurs.",
    painPoints: [
      "Dépendance aux portails payants (SeLoger, LeBonCoin)",
      "Difficulté à générer des mandats",
      "Biens mal mis en valeur",
      "Pas d'estimation en ligne",
    ],
    solutions: [
      { title: "Portail d'annonces intégré", description: "Vos biens présentés avec photos HD, visites virtuelles" },
      { title: "Estimation en ligne", description: "Captez des vendeurs avec un outil d'estimation automatique" },
      { title: "Alertes email", description: "Les acquéreurs reçoivent les nouveaux biens correspondants" },
      { title: "CRM intégré", description: "Gérez vos contacts et suivis directement depuis le site" },
    ],
    specificFeatures: ["Recherche avancée", "Carte interactive", "Visite virtuelle 360°", "Matching acquéreurs"],
    digitalServices: ["site_web", "seo_local", "google_ads", "facebook_ads", "crm", "automation", "emailing", "avis_google", "analytics", "app_mobile"],
    stats: [
      { label: "Contacts acquéreurs", value: "+70%" },
      { label: "Mandats générés", value: "+45%" },
      { label: "Coût portails réduit", value: "-30%" },
    ],
    faqs: [
      { question: "Le site peut-il se synchroniser avec les portails ?", answer: "Oui, nous pouvons mettre en place une passerelle vers SeLoger, LeBonCoin, etc." },
      { question: "Comment fonctionne l'estimation en ligne ?", answer: "Un formulaire collecte les informations du bien et génère une fourchette de prix basée sur les données du marché." },
    ],
  },
  {
    slug: "architecte",
    name: "Architecte",
    namePlural: "Architectes",
    icon: "Compass",
    category: "services",
    metaTitle: "Site Web Architecte | Portfolio Architecture",
    metaDescription: "Création site portfolio pour architecte. Présentez vos projets et réalisations. Design élégant pour mettre en valeur votre travail.",
    headline: "Un portfolio qui met en lumière vos projets",
    subheadline: "Un site élégant et visuel pour présenter vos réalisations architecturales et attirer de nouveaux clients.",
    painPoints: [
      "Projets difficiles à présenter sans site",
      "Concurrence importante dans le secteur",
      "Besoin de montrer son style et sa vision",
      "Clients qui ne comprennent pas le processus",
    ],
    solutions: [
      { title: "Portfolio immersif", description: "Galeries photos et vidéos de vos réalisations" },
      { title: "Études de cas détaillées", description: "Présentez le processus de A à Z pour chaque projet" },
      { title: "Présentation de l'agence", description: "Votre philosophie, votre équipe, vos valeurs" },
      { title: "Contact qualifié", description: "Formulaire détaillé pour qualifier les projets" },
    ],
    specificFeatures: ["Galerie plein écran", "Filtres par type de projet", "Plans et croquis", "Témoignages clients"],
    digitalServices: ["site_web", "seo_local", "google_ads", "reseaux_sociaux", "avis_google", "crm"],
    stats: [
      { label: "Demandes de projets", value: "+50%" },
      { label: "Qualité des leads", value: "+60%" },
      { label: "Notoriété", value: "+80%" },
    ],
    faqs: [
      { question: "Puis-je ajouter des projets moi-même ?", answer: "Oui, le back-office vous permet d'ajouter facilement de nouveaux projets avec photos et descriptions." },
      { question: "Le site sera-t-il responsive ?", answer: "Absolument, votre portfolio sera magnifique sur tous les écrans, du mobile au grand écran." },
    ],
  },
  {
    slug: "consultant",
    name: "Consultant",
    namePlural: "Consultants",
    icon: "Briefcase",
    category: "services",
    metaTitle: "Site Web Consultant | Personal Branding",
    metaDescription: "Création site internet consultant indépendant. Personal branding, expertise, génération de leads B2B. Solution professionnelle.",
    headline: "Positionnez-vous comme expert de votre domaine",
    subheadline: "Un site personnel qui établit votre crédibilité et génère des opportunités de mission.",
    painPoints: [
      "Difficulté à se positionner comme expert",
      "Dépendance au bouche-à-oreille",
      "Pas de visibilité en ligne",
      "Concurrence des grandes structures",
    ],
    solutions: [
      { title: "Personal branding", description: "Votre parcours, expertise et valeur ajoutée mis en avant" },
      { title: "Cas clients", description: "Présentez vos missions réussies et leurs résultats" },
      { title: "Blog d'expertise", description: "Publiez des articles pour démontrer votre savoir-faire" },
      { title: "Lead magnet", description: "Captez des emails avec un livre blanc ou une checklist" },
    ],
    specificFeatures: ["Témoignages clients", "Parcours détaillé", "Publications", "Prise de RDV"],
    digitalServices: ["site_web", "seo_local", "google_ads", "reseaux_sociaux", "emailing", "crm", "automation", "reservation"],
    stats: [
      { label: "Demandes de mission", value: "+70%" },
      { label: "Crédibilité perçue", value: "+90%" },
      { label: "Tarif journalier", value: "+20%" },
    ],
    faqs: [
      { question: "Comment générer des leads ?", answer: "Nous mettons en place des stratégies de content marketing et des lead magnets pour capturer des contacts qualifiés." },
      { question: "Puis-je publier mes articles LinkedIn sur le site ?", answer: "Oui, vous pouvez republier vos contenus et même automatiser la synchronisation." },
    ],
  },

  // ============================================
  // SANTÉ & BIEN-ÊTRE
  // ============================================
  {
    slug: "medecin",
    name: "Médecin",
    namePlural: "Médecins",
    icon: "Stethoscope",
    category: "sante",
    metaTitle: "Site Web Médecin | Cabinet Médical",
    metaDescription: "Création site internet cabinet médical. Prise de RDV en ligne, informations patients. Conforme RGPD et déontologie médicale.",
    headline: "Votre cabinet accessible en ligne",
    subheadline: "Un site pratique pour vos patients avec prise de rendez-vous et informations médicales.",
    painPoints: [
      "Standard téléphonique saturé",
      "Patients mal informés avant consultation",
      "Pas de prise de RDV hors horaires",
      "Questions répétitives des patients",
    ],
    solutions: [
      { title: "Prise de RDV Doctolib/Maiia", description: "Intégration des principales plateformes de RDV médicaux" },
      { title: "Fiches pathologies", description: "Informez vos patients sur les maladies courantes" },
      { title: "Préparation consultation", description: "Documents et informations à amener" },
      { title: "Téléconsultation", description: "Intégration de solutions de consultation vidéo" },
    ],
    specificFeatures: ["Horaires et urgences", "Parcours patient", "Équipe médicale", "Accès cabinet"],
    digitalServices: ["site_web", "seo_local", "reservation", "avis_google", "chatbot", "emailing", "app_mobile", "crm"],
    stats: [
      { label: "Appels réduits", value: "-45%" },
      { label: "RDV en ligne", value: "+80%" },
      { label: "Satisfaction patients", value: "+35%" },
    ],
    faqs: [
      { question: "Le site est-il conforme au RGPD ?", answer: "Absolument, nous respectons toutes les obligations de protection des données de santé." },
      { question: "Peut-on intégrer Doctolib ?", answer: "Oui, nous intégrons le widget de prise de RDV Doctolib, Maiia ou Keldoc directement sur votre site." },
    ],
  },
  {
    slug: "dentiste",
    name: "Dentiste",
    namePlural: "Dentistes",
    icon: "HeartPulse",
    category: "sante",
    metaTitle: "Site Web Dentiste | Cabinet Dentaire",
    metaDescription: "Création site internet cabinet dentaire. Prise de RDV, présentation des soins. Rassurez vos patients avec un site professionnel.",
    headline: "Un sourire digital pour votre cabinet",
    subheadline: "Rassurez vos patients avec un site clair présentant vos soins et facilitant la prise de rendez-vous.",
    painPoints: [
      "Patients anxieux mal informés",
      "Soins mal compris (implants, orthodontie)",
      "Beaucoup d'appels pour les urgences",
      "Image du cabinet à moderniser",
    ],
    solutions: [
      { title: "Présentation des soins", description: "Expliquez chaque type de soin avec des visuels rassurants" },
      { title: "Avant/Après", description: "Montrez vos résultats en esthétique dentaire" },
      { title: "Gestion des urgences", description: "Protocole clair pour les urgences dentaires" },
      { title: "Visite virtuelle", description: "Faites découvrir votre cabinet moderne" },
    ],
    specificFeatures: ["Galerie sourires", "Équipements", "Équipe", "Devis en ligne"],
    digitalServices: ["site_web", "seo_local", "reservation", "avis_google", "google_ads", "emailing", "chatbot"],
    stats: [
      { label: "Nouveaux patients", value: "+40%" },
      { label: "Anxiété réduite", value: "+50%" },
      { label: "Soins esthétiques", value: "+35%" },
    ],
    faqs: [
      { question: "Peut-on montrer des photos avant/après ?", answer: "Oui, avec le consentement des patients, nous créons une galerie de résultats très efficace pour l'esthétique dentaire." },
      { question: "Comment gérer les urgences via le site ?", answer: "Nous mettons en place un protocole clair avec numéro d'urgence et instructions." },
    ],
  },
  {
    slug: "kinesitherapeute",
    name: "Kinésithérapeute",
    namePlural: "Kinésithérapeutes",
    icon: "Activity",
    category: "sante",
    metaTitle: "Site Web Kinésithérapeute | Cabinet Kiné",
    metaDescription: "Création site internet kinésithérapeute. Présentez vos spécialités, facilitez la prise de RDV. Solution adaptée aux kinés.",
    headline: "Votre expertise kiné mise en avant",
    subheadline: "Présentez vos spécialités et permettez à vos patients de prendre rendez-vous facilement.",
    painPoints: [
      "Spécialités mal connues des patients",
      "Concurrence importante",
      "Patients qui ne préparent pas leurs séances",
      "Gestion des RDV chronophage",
    ],
    solutions: [
      { title: "Spécialités détaillées", description: "Sport, respiratoire, neurologie... présentez vos expertises" },
      { title: "Prise de RDV en ligne", description: "Synchronisation avec votre agenda" },
      { title: "Exercices en ligne", description: "Vidéos d'exercices à faire entre les séances" },
      { title: "Blog santé", description: "Conseils prévention et rééducation" },
    ],
    specificFeatures: ["Vidéos exercices", "Pathologies traitées", "Équipements", "Tarifs et remboursements"],
    digitalServices: ["site_web", "seo_local", "reservation", "avis_google", "emailing", "automation"],
    stats: [
      { label: "Nouveaux patients", value: "+45%" },
      { label: "Compliance exercices", value: "+60%" },
      { label: "Fidélisation", value: "+30%" },
    ],
    faqs: [
      { question: "Puis-je partager des vidéos d'exercices ?", answer: "Oui, nous créons une bibliothèque vidéo accessible à vos patients pour leurs exercices à domicile." },
      { question: "Le site peut-il gérer plusieurs praticiens ?", answer: "Absolument, chaque kiné du cabinet peut avoir sa fiche et son agenda." },
    ],
  },
  {
    slug: "psychologue",
    name: "Psychologue",
    namePlural: "Psychologues",
    icon: "Brain",
    category: "sante",
    metaTitle: "Site Web Psychologue | Cabinet Psychologie",
    metaDescription: "Création site internet psychologue. Présentez votre approche thérapeutique, rassurez vos patients. Site confidentiel et professionnel.",
    headline: "Un premier contact bienveillant en ligne",
    subheadline: "Un site rassurant qui présente votre approche et facilite le premier pas vers la thérapie.",
    painPoints: [
      "Patients hésitants à franchir le pas",
      "Approche thérapeutique mal comprise",
      "Besoin de rassurer avant le premier RDV",
      "Gestion des RDV et annulations",
    ],
    solutions: [
      { title: "Présentation bienveillante", description: "Votre parcours et approche thérapeutique expliqués simplement" },
      { title: "FAQ rassurante", description: "Répondez aux questions que se posent les nouveaux patients" },
      { title: "Prise de RDV confidentielle", description: "Formulaire sécurisé et discret" },
      { title: "Ressources", description: "Articles et podcasts sur la santé mentale" },
    ],
    specificFeatures: ["Approches thérapeutiques", "Publics accompagnés", "Tarifs", "Premier RDV"],
    digitalServices: ["site_web", "seo_local", "reservation", "avis_google", "emailing"],
    stats: [
      { label: "Demandes de RDV", value: "+55%" },
      { label: "Réassurance patients", value: "+70%" },
      { label: "Annulations réduites", value: "-25%" },
    ],
    faqs: [
      { question: "Comment rassurer les patients hésitants ?", answer: "Nous créons un contenu bienveillant expliquant le déroulement d'une thérapie et démystifiant la consultation psy." },
      { question: "La confidentialité est-elle assurée ?", answer: "Absolument, le formulaire de contact est sécurisé et aucune donnée n'est partagée." },
    ],
  },
  {
    slug: "osteopathe",
    name: "Ostéopathe",
    namePlural: "Ostéopathes",
    icon: "Hand",
    category: "sante",
    metaTitle: "Site Web Ostéopathe | Cabinet Ostéopathie",
    metaDescription: "Création site internet ostéopathe. Expliquez l'ostéopathie, présentez vos spécialités. Attirez de nouveaux patients.",
    headline: "L'ostéopathie expliquée et accessible",
    subheadline: "Un site qui démystifie l'ostéopathie et présente clairement les pathologies que vous traitez.",
    painPoints: [
      "Ostéopathie mal comprise du grand public",
      "Patients qui ne savent pas quand consulter",
      "Concurrence nombreuse",
      "Besoin de se spécialiser",
    ],
    solutions: [
      { title: "Pédagogie ostéo", description: "Expliquez simplement ce qu'est l'ostéopathie" },
      { title: "Motifs de consultation", description: "Listez les pathologies que vous traitez" },
      { title: "Spécialités", description: "Sport, bébés, femmes enceintes... mettez en avant vos expertises" },
      { title: "Conseils prévention", description: "Blog avec conseils posture et bien-être" },
    ],
    specificFeatures: ["Déroulement séance", "Tarifs et mutuelles", "Urgences", "Blog santé"],
    digitalServices: ["site_web", "seo_local", "reservation", "avis_google", "google_ads", "emailing"],
    stats: [
      { label: "Nouveaux patients", value: "+50%" },
      { label: "Compréhension ostéo", value: "+80%" },
      { label: "Fidélisation", value: "+35%" },
    ],
    faqs: [
      { question: "Comment expliquer l'ostéopathie simplement ?", answer: "Nous créons des contenus pédagogiques avec schémas et vidéos pour expliquer votre pratique." },
      { question: "Puis-je cibler une spécialité ?", answer: "Oui, nous optimisons le site pour vos spécialités (sport, pédiatrie, etc.) pour un meilleur référencement." },
    ],
  },
  {
    slug: "salon-coiffure",
    name: "Salon de Coiffure",
    namePlural: "Salons de Coiffure",
    icon: "Scissors",
    category: "sante",
    metaTitle: "Site Web Salon de Coiffure | Réservation en ligne",
    metaDescription: "Création site internet salon de coiffure. Réservation en ligne, galerie réalisations. Modernisez votre salon.",
    headline: "Votre salon visible et accessible 24/7",
    subheadline: "Un site moderne avec réservation en ligne pour remplir votre planning.",
    painPoints: [
      "Standard téléphonique difficile à gérer",
      "Créneaux non remplis",
      "Clients qui ne connaissent pas tous vos services",
      "Image à moderniser",
    ],
    solutions: [
      { title: "Réservation en ligne", description: "Vos clients réservent leur créneau 24h/24" },
      { title: "Galerie réalisations", description: "Montrez vos coupes et colorations" },
      { title: "Carte des services", description: "Tous vos services et tarifs présentés clairement" },
      { title: "Équipe", description: "Présentez vos coiffeurs et leurs spécialités" },
    ],
    specificFeatures: ["Intégration Planity/Treatwell", "Promotions", "Produits", "Avis clients"],
    digitalServices: ["site_web", "seo_local", "reservation", "avis_google", "reseaux_sociaux", "facebook_ads", "emailing", "ecommerce", "app_mobile", "crm"],
    stats: [
      { label: "Réservations en ligne", value: "+60%" },
      { label: "No-shows réduits", value: "-40%" },
      { label: "Nouveaux clients", value: "+35%" },
    ],
    faqs: [
      { question: "Quel système de réservation intégrer ?", answer: "Nous intégrons Planity, Treatwell, ou un système personnalisé selon vos préférences." },
      { question: "Puis-je vendre mes produits en ligne ?", answer: "Oui, nous pouvons ajouter une boutique pour vos produits capillaires." },
    ],
  },
  {
    slug: "institut-beaute",
    name: "Institut de Beauté",
    namePlural: "Instituts de Beauté",
    icon: "Sparkles",
    category: "sante",
    metaTitle: "Site Web Institut de Beauté | Spa & Esthétique",
    metaDescription: "Création site internet institut de beauté, spa, esthétique. Réservation en ligne, carte des soins. Solution élégante.",
    headline: "L'élégance de votre institut en ligne",
    subheadline: "Un site raffiné qui présente vos soins et permet la réservation en ligne.",
    painPoints: [
      "Clients qui ne connaissent pas tous vos soins",
      "Gestion des RDV chronophage",
      "Concurrence des chaînes",
      "Besoin de mettre en avant l'ambiance",
    ],
    solutions: [
      { title: "Carte des soins", description: "Présentez chaque soin avec durée, prix et bénéfices" },
      { title: "Réservation en ligne", description: "Réservation 24/7 avec choix du praticien" },
      { title: "Forfaits et abonnements", description: "Mettez en avant vos offres fidélité" },
      { title: "Ambiance immersive", description: "Photos et vidéos de votre institut" },
    ],
    specificFeatures: ["Carte cadeau en ligne", "Avis clients", "Blog beauté", "Équipe"],
    digitalServices: ["site_web", "seo_local", "reservation", "avis_google", "reseaux_sociaux", "facebook_ads", "emailing", "ecommerce", "crm", "app_mobile"],
    stats: [
      { label: "Réservations", value: "+55%" },
      { label: "Panier moyen", value: "+25%" },
      { label: "Fidélisation", value: "+40%" },
    ],
    faqs: [
      { question: "Peut-on vendre des cartes cadeaux en ligne ?", answer: "Oui, nous intégrons un système de bons cadeaux à offrir directement depuis le site." },
      { question: "Comment mettre en avant l'ambiance ?", answer: "Nous créons une expérience visuelle immersive avec photos professionnelles et vidéos." },
    ],
  },

  // ============================================
  // ARTISANAT & BTP
  // ============================================
  {
    slug: "plombier",
    name: "Plombier",
    namePlural: "Plombiers",
    icon: "Wrench",
    category: "artisanat",
    metaTitle: "Site Web Plombier | Dépannage & Installation",
    metaDescription: "Création site internet plombier. Urgences, devis en ligne, zone d'intervention. Générez des appels de clients locaux.",
    headline: "Soyez le plombier trouvé en premier sur Google",
    subheadline: "Un site optimisé pour le référencement local qui génère des appels de clients dans votre zone.",
    painPoints: [
      "Dépendance aux plateformes (Pages Jaunes, etc.)",
      "Difficulté à se différencier",
      "Clients qui comparent les prix",
      "Urgences mal gérées",
    ],
    solutions: [
      { title: "SEO local puissant", description: "Apparaissez en premier pour 'plombier + votre ville'" },
      { title: "Appel en un clic", description: "Bouton d'appel visible sur mobile" },
      { title: "Devis en ligne", description: "Formulaire de demande de devis rapide" },
      { title: "Zone d'intervention", description: "Carte claire de vos communes desservies" },
    ],
    specificFeatures: ["Urgences 24/7", "Tarifs indicatifs", "Réalisations", "Avis Google"],
    digitalServices: ["site_web", "seo_local", "google_ads", "avis_google", "crm", "automation"],
    stats: [
      { label: "Appels entrants", value: "+80%" },
      { label: "Visibilité Google", value: "+120%" },
      { label: "Devis convertis", value: "+40%" },
    ],
    faqs: [
      { question: "Comment remonter sur Google ?", answer: "Nous optimisons votre site pour le SEO local avec Google My Business, avis clients et mots-clés géolocalisés." },
      { question: "Les urgences sont-elles mises en avant ?", answer: "Oui, un bandeau d'urgence avec numéro de téléphone est visible en permanence." },
    ],
  },
  {
    slug: "electricien",
    name: "Électricien",
    namePlural: "Électriciens",
    icon: "Zap",
    category: "artisanat",
    metaTitle: "Site Web Électricien | Dépannage & Installation",
    metaDescription: "Création site internet électricien. Urgences, mise aux normes, devis en ligne. Développez votre clientèle locale.",
    headline: "L'électricien de confiance de votre secteur",
    subheadline: "Un site professionnel qui rassure et génère des demandes d'intervention.",
    painPoints: [
      "Clients méfiants (arnaques dans le secteur)",
      "Besoin de prouver ses qualifications",
      "Concurrence des grandes enseignes",
      "Urgences difficiles à gérer",
    ],
    solutions: [
      { title: "Certifications mises en avant", description: "Affichez vos qualifications Qualifelec, garanties décennales" },
      { title: "Réalisations avec photos", description: "Montrez vos chantiers pour rassurer" },
      { title: "Devis rapide", description: "Formulaire simplifié pour demandes urgentes" },
      { title: "Avis clients vérifiés", description: "Intégration Google Reviews" },
    ],
    specificFeatures: ["Urgences électriques", "Mise aux normes", "Domotique", "Bornes de recharge"],
    digitalServices: ["site_web", "seo_local", "google_ads", "avis_google", "crm", "automation"],
    stats: [
      { label: "Demandes de devis", value: "+70%" },
      { label: "Confiance clients", value: "+60%" },
      { label: "Chantiers domotique", value: "+45%" },
    ],
    faqs: [
      { question: "Comment rassurer les clients sur ma fiabilité ?", answer: "Nous mettons en avant vos certifications, assurances et avis clients vérifiés." },
      { question: "Puis-je proposer la domotique ?", answer: "Oui, une section dédiée peut présenter vos services de maison connectée." },
    ],
  },
  {
    slug: "menuisier",
    name: "Menuisier",
    namePlural: "Menuisiers",
    icon: "Hammer",
    category: "artisanat",
    metaTitle: "Site Web Menuisier | Menuiserie sur mesure",
    metaDescription: "Création site internet menuisier. Portfolio réalisations, devis en ligne. Mettez en valeur votre savoir-faire artisanal.",
    headline: "Votre savoir-faire artisanal en vitrine",
    subheadline: "Un portfolio élégant qui met en valeur vos créations et génère des demandes de projet.",
    painPoints: [
      "Difficile de montrer son travail sans site",
      "Clients qui ne comprennent pas le sur-mesure",
      "Concurrence du mobilier industriel",
      "Besoin de justifier les prix",
    ],
    solutions: [
      { title: "Portfolio réalisations", description: "Galerie photos de vos créations (cuisines, escaliers, mobilier)" },
      { title: "Processus expliqué", description: "De la conception à la pose, rassurez vos clients" },
      { title: "Essences de bois", description: "Présentez les matériaux que vous travaillez" },
      { title: "Devis personnalisé", description: "Formulaire détaillé pour projets sur mesure" },
    ],
    specificFeatures: ["Galerie avant/après", "Certifications RGE", "Partenaires", "Blog conseils"],
    digitalServices: ["site_web", "seo_local", "google_ads", "avis_google", "reseaux_sociaux", "crm"],
    stats: [
      { label: "Demandes qualifiées", value: "+65%" },
      { label: "Panier moyen", value: "+30%" },
      { label: "Notoriété locale", value: "+80%" },
    ],
    faqs: [
      { question: "Comment valoriser le sur-mesure ?", answer: "Nous créons des études de cas détaillées montrant le processus de création et la valeur ajoutée du sur-mesure." },
      { question: "Les photos sont-elles importantes ?", answer: "Essentielles ! Nous vous conseillons sur la prise de vue ou pouvons organiser un shooting professionnel." },
    ],
  },
  {
    slug: "peintre-batiment",
    name: "Peintre en Bâtiment",
    namePlural: "Peintres en Bâtiment",
    icon: "PaintBucket",
    category: "artisanat",
    metaTitle: "Site Web Peintre en Bâtiment | Travaux de peinture",
    metaDescription: "Création site internet peintre en bâtiment. Réalisations, devis en ligne. Développez votre activité de peinture.",
    headline: "Vos talents de peintre en lumière",
    subheadline: "Un site avec galerie avant/après qui transforme les visiteurs en clients.",
    painPoints: [
      "Concurrence importante",
      "Difficulté à montrer la qualité du travail",
      "Clients qui comparent uniquement sur le prix",
      "Besoin de prouver son sérieux",
    ],
    solutions: [
      { title: "Galerie avant/après", description: "L'impact visuel de votre travail en images" },
      { title: "Spécialités", description: "Façades, intérieurs, décoratif, industriel..." },
      { title: "Devis rapide", description: "Formulaire avec upload de photos" },
      { title: "Garanties", description: "Assurances et certifications mises en avant" },
    ],
    specificFeatures: ["Nuancier en ligne", "Conseil couleurs", "Zone intervention", "Avis clients"],
    digitalServices: ["site_web", "seo_local", "google_ads", "avis_google", "crm"],
    stats: [
      { label: "Demandes de devis", value: "+75%" },
      { label: "Taux de conversion", value: "+40%" },
      { label: "Chantiers déco", value: "+50%" },
    ],
    faqs: [
      { question: "Les photos avant/après sont-elles efficaces ?", answer: "Absolument, c'est le meilleur argument de vente pour un peintre. L'impact visuel est immédiat." },
      { question: "Puis-je proposer du conseil couleurs ?", answer: "Oui, nous pouvons intégrer un outil de simulation couleurs ou un formulaire de conseil déco." },
    ],
  },
  {
    slug: "couvreur",
    name: "Couvreur",
    namePlural: "Couvreurs",
    icon: "HardHat",
    category: "artisanat",
    metaTitle: "Site Web Couvreur | Toiture & Charpente",
    metaDescription: "Création site internet couvreur. Urgences toiture, devis en ligne, réalisations. Développez votre entreprise de couverture.",
    headline: "Le couvreur de référence de votre région",
    subheadline: "Un site qui génère des demandes d'intervention et des projets de rénovation.",
    painPoints: [
      "Urgences (fuites, tempêtes) mal gérées",
      "Clients qui ne font pas de prévention",
      "Concurrence sur les prix",
      "Difficulté à montrer son travail (toits)",
    ],
    solutions: [
      { title: "Urgences toiture", description: "Numéro d'urgence visible, intervention rapide" },
      { title: "Types de toitures", description: "Tuiles, ardoises, zinc... présentez vos spécialités" },
      { title: "Réalisations drone", description: "Photos aériennes de vos chantiers" },
      { title: "Entretien préventif", description: "Proposez des contrats de maintenance" },
    ],
    specificFeatures: ["Devis toiture", "Isolation", "Panneaux solaires", "RGE"],
    digitalServices: ["site_web", "seo_local", "google_ads", "avis_google", "crm", "automation"],
    stats: [
      { label: "Appels urgences", value: "+60%" },
      { label: "Contrats entretien", value: "+45%" },
      { label: "Projets rénovation", value: "+55%" },
    ],
    faqs: [
      { question: "Comment montrer des toitures ?", answer: "Nous utilisons des photos drone ou depuis le sol avec zoom. Les avant/après sont très efficaces." },
      { question: "Puis-je proposer des contrats d'entretien ?", answer: "Oui, c'est un excellent moyen de fidéliser et de générer des revenus récurrents." },
    ],
  },
  {
    slug: "jardinier-paysagiste",
    name: "Jardinier Paysagiste",
    namePlural: "Jardiniers Paysagistes",
    icon: "TreeDeciduous",
    category: "artisanat",
    metaTitle: "Site Web Paysagiste | Création de jardins",
    metaDescription: "Création site internet jardinier paysagiste. Portfolio jardins, devis en ligne. Mettez en valeur vos créations paysagères.",
    headline: "Vos créations paysagères en portfolio",
    subheadline: "Un site visuel qui met en valeur vos jardins et attire des projets d'aménagement.",
    painPoints: [
      "Travail difficile à présenter sans photos",
      "Clients qui sous-estiment les coûts",
      "Saisonnalité de l'activité",
      "Concurrence nombreuse",
    ],
    solutions: [
      { title: "Portfolio projets", description: "Galeries par type de jardin (contemporain, japonais, potager...)" },
      { title: "Entretien régulier", description: "Proposez des contrats annuels pour lisser l'activité" },
      { title: "Blog conseils", description: "Positionnez-vous comme expert jardin" },
      { title: "Devis détaillé", description: "Formulaire avec surface, style souhaité, budget" },
    ],
    specificFeatures: ["Avant/après", "Plantes utilisées", "Saisons", "Éco-responsable"],
    digitalServices: ["site_web", "seo_local", "google_ads", "avis_google", "reseaux_sociaux", "crm", "automation"],
    stats: [
      { label: "Projets création", value: "+70%" },
      { label: "Contrats entretien", value: "+50%" },
      { label: "Panier moyen", value: "+35%" },
    ],
    faqs: [
      { question: "Les photos de jardins sont-elles essentielles ?", answer: "Absolument, c'est votre meilleur argument. Nous vous conseillons de photographier vos réalisations à différentes saisons." },
      { question: "Comment proposer l'entretien régulier ?", answer: "Nous créons une page dédiée avec les formules d'abonnement et leurs avantages." },
    ],
  },

  // ============================================
  // RESTAURATION & ALIMENTATION
  // ============================================
  {
    slug: "traiteur",
    name: "Traiteur",
    namePlural: "Traiteurs",
    icon: "ChefHat",
    category: "commerce",
    metaTitle: "Site Web Traiteur | Événements & Réceptions",
    metaDescription: "Création site internet traiteur. Présentez vos prestations, galerie événements. Générez des demandes de devis.",
    headline: "Vos créations culinaires méritent une vitrine",
    subheadline: "Un site appétissant qui présente vos prestations et génère des demandes d'événements.",
    painPoints: [
      "Difficile de montrer ses prestations",
      "Clients qui ne connaissent pas toutes les formules",
      "Beaucoup de temps en devis",
      "Concurrence des grandes enseignes",
    ],
    solutions: [
      { title: "Galerie événements", description: "Photos de vos buffets, cocktails, mariages" },
      { title: "Formules et menus", description: "Présentez vos offres clairement avec tarifs" },
      { title: "Devis en ligne", description: "Formulaire détaillé (date, nombre de convives, type)" },
      { title: "Témoignages", description: "Avis de mariés et organisateurs d'événements" },
    ],
    specificFeatures: ["Calendrier disponibilités", "Menus saisonniers", "Prestations à emporter", "Partenaires"],
    digitalServices: ["site_web", "seo_local", "avis_google", "reseaux_sociaux", "facebook_ads", "crm", "emailing"],
    stats: [
      { label: "Demandes de devis", value: "+65%" },
      { label: "Mariages", value: "+40%" },
      { label: "Entreprises", value: "+50%" },
    ],
    faqs: [
      { question: "Comment présenter mes formules ?", answer: "Nous créons des pages par type d'événement (mariage, entreprise, particulier) avec les formules adaptées." },
      { question: "Puis-je montrer mes disponibilités ?", answer: "Oui, un calendrier peut indiquer les dates déjà réservées pour éviter les demandes inutiles." },
    ],
  },
  {
    slug: "cave-vins",
    name: "Cave à Vins",
    namePlural: "Caves à Vins",
    icon: "Wine",
    category: "commerce",
    metaTitle: "Site Web Cave à Vins | Caviste en ligne",
    metaDescription: "Création site internet cave à vins. Catalogue en ligne, dégustations, livraison. Développez votre clientèle de caviste.",
    headline: "Votre passion du vin accessible en ligne",
    subheadline: "Un site élégant pour présenter votre sélection et vendre en ligne.",
    painPoints: [
      "Clients limités au quartier",
      "Difficulté à présenter la sélection",
      "Concurrence des sites de vente en ligne",
      "Événements peu connus",
    ],
    solutions: [
      { title: "Catalogue en ligne", description: "Présentez vos vins par région, cépage, occasion" },
      { title: "E-commerce", description: "Vente en ligne avec livraison ou retrait" },
      { title: "Événements", description: "Dégustations, cours d'œnologie, soirées accords" },
      { title: "Conseils sommelier", description: "Blog et guides d'accords mets-vins" },
    ],
    specificFeatures: ["Fiches vins détaillées", "Notes et médailles", "Coffrets cadeaux", "Abonnements"],
    digitalServices: ["site_web", "seo_local", "ecommerce", "avis_google", "reseaux_sociaux", "emailing", "crm", "app_mobile"],
    stats: [
      { label: "Ventes en ligne", value: "+80%" },
      { label: "Inscriptions dégustations", value: "+60%" },
      { label: "Zone de chalandise", value: "x4" },
    ],
    faqs: [
      { question: "Comment présenter mes vins efficacement ?", answer: "Chaque vin a sa fiche avec photo, description, accords, et notes si disponibles." },
      { question: "La livraison de vin est-elle complexe ?", answer: "Nous intégrons des transporteurs spécialisés et gérons les restrictions légales (vérification d'âge)." },
    ],
  },

  // ============================================
  // ÉDUCATION & FORMATION
  // ============================================
  {
    slug: "auto-ecole",
    name: "Auto-École",
    namePlural: "Auto-Écoles",
    icon: "Car",
    category: "services",
    metaTitle: "Site Web Auto-École | Inscription en ligne",
    metaDescription: "Création site internet auto-école. Inscription en ligne, tarifs, code de la route. Attirez de nouveaux élèves.",
    headline: "Remplissez vos sessions de formation",
    subheadline: "Un site moderne qui présente vos formations et permet l'inscription en ligne.",
    painPoints: [
      "Concurrence avec les plateformes en ligne",
      "Élèves qui comparent les prix",
      "Inscriptions chronophages",
      "Réputation difficile à montrer",
    ],
    solutions: [
      { title: "Inscription en ligne", description: "Formulaire d'inscription avec paiement sécurisé" },
      { title: "Formations détaillées", description: "Permis B, A, AAC... avec tarifs et durées" },
      { title: "Taux de réussite", description: "Affichez vos statistiques pour rassurer" },
      { title: "Avis élèves", description: "Témoignages de vos anciens élèves" },
    ],
    specificFeatures: ["Code en ligne", "Planning moniteurs", "Simulateur", "FAQ permis"],
    digitalServices: ["site_web", "seo_local", "google_ads", "avis_google", "reservation", "crm", "automation", "emailing", "app_mobile"],
    stats: [
      { label: "Inscriptions en ligne", value: "+55%" },
      { label: "Demandes d'info", value: "+70%" },
      { label: "Conversion prospects", value: "+40%" },
    ],
    faqs: [
      { question: "Peut-on proposer le code en ligne ?", answer: "Oui, nous intégrons les plateformes de code en ligne ou créons un accès dédié." },
      { question: "Comment afficher le planning ?", answer: "Un calendrier peut montrer les disponibilités des moniteurs pour la réservation." },
    ],
  },
  {
    slug: "centre-formation",
    name: "Centre de Formation",
    namePlural: "Centres de Formation",
    icon: "GraduationCap",
    category: "services",
    metaTitle: "Site Web Centre de Formation | Organisme formateur",
    metaDescription: "Création site internet centre de formation. Catalogue formations, inscription en ligne, certifications. Solution complète.",
    headline: "Vos formations accessibles en un clic",
    subheadline: "Un site professionnel pour présenter votre offre et gérer les inscriptions.",
    painPoints: [
      "Catalogue de formations difficile à présenter",
      "Inscriptions manuelles chronophages",
      "Certifications mal mises en avant",
      "Concurrence du e-learning",
    ],
    solutions: [
      { title: "Catalogue formations", description: "Fiches détaillées par formation (programme, durée, prix)" },
      { title: "Inscription en ligne", description: "Formulaire d'inscription avec documents requis" },
      { title: "Certifications", description: "Qualiopi, CPF, OPCO... mises en avant" },
      { title: "Espace stagiaire", description: "Accès aux supports et évaluations" },
    ],
    specificFeatures: ["Calendrier sessions", "Financement CPF", "Témoignages", "Blog expertise"],
    digitalServices: ["site_web", "seo_local", "google_ads", "crm", "automation", "emailing", "chatbot", "analytics", "app_mobile"],
    stats: [
      { label: "Inscriptions", value: "+60%" },
      { label: "Dossiers CPF", value: "+45%" },
      { label: "Notoriété", value: "+80%" },
    ],
    faqs: [
      { question: "Comment intégrer le CPF ?", answer: "Nous affichons les formations éligibles et facilitons le parcours vers MonCompteFormation." },
      { question: "Peut-on créer un espace stagiaire ?", answer: "Oui, avec accès sécurisé aux supports de cours, quiz et attestations." },
    ],
  },
  {
    slug: "coach-sportif",
    name: "Coach Sportif",
    namePlural: "Coachs Sportifs",
    icon: "Dumbbell",
    category: "sante",
    metaTitle: "Site Web Coach Sportif | Personal Training",
    metaDescription: "Création site internet coach sportif personnel. Réservation séances, programmes, témoignages. Développez votre clientèle.",
    headline: "Votre expertise fitness en ligne",
    subheadline: "Un site motivant qui présente vos services et permet la réservation de séances.",
    painPoints: [
      "Clientèle limitée au bouche-à-oreille",
      "Difficulté à se différencier",
      "Gestion des RDV manuelle",
      "Pas de revenus passifs",
    ],
    solutions: [
      { title: "Réservation en ligne", description: "Vos clients réservent leurs séances en autonomie" },
      { title: "Programmes en ligne", description: "Vendez des programmes d'entraînement digitaux" },
      { title: "Transformations", description: "Galerie avant/après de vos clients" },
      { title: "Blog fitness", description: "Conseils nutrition et entraînement" },
    ],
    specificFeatures: ["Spécialités", "Tarifs et packs", "Témoignages vidéo", "Zone intervention"],
    digitalServices: ["site_web", "seo_local", "reservation", "reseaux_sociaux", "facebook_ads", "ecommerce", "emailing", "crm", "app_mobile"],
    stats: [
      { label: "Réservations", value: "+70%" },
      { label: "Ventes programmes", value: "+50%" },
      { label: "Fidélisation", value: "+45%" },
    ],
    faqs: [
      { question: "Puis-je vendre des programmes en ligne ?", answer: "Oui, nous créons un espace de vente avec paiement sécurisé et livraison automatique des programmes PDF ou vidéo." },
      { question: "Comment montrer les transformations ?", answer: "Une galerie avant/après avec l'accord des clients est très efficace pour convaincre." },
    ],
  },

  // ============================================
  // TECH & DIGITAL
  // ============================================
  {
    slug: "photographe",
    name: "Photographe",
    namePlural: "Photographes",
    icon: "Camera",
    category: "tech",
    metaTitle: "Site Web Photographe | Portfolio Photo",
    metaDescription: "Création site portfolio photographe. Galeries, réservation séances, vente tirages. Mettez en valeur votre travail.",
    headline: "Un portfolio à la hauteur de votre talent",
    subheadline: "Un site élégant qui met en valeur vos photos et génère des demandes de shooting.",
    painPoints: [
      "Instagram ne suffit plus",
      "Besoin d'un portfolio professionnel",
      "Difficile de vendre des tirages",
      "Gestion des RDV manuelle",
    ],
    solutions: [
      { title: "Portfolio immersif", description: "Galeries plein écran par type de shooting" },
      { title: "Réservation séances", description: "Calendrier de disponibilités et paiement d'acompte" },
      { title: "Vente de tirages", description: "Boutique pour vendre vos photos en tirage" },
      { title: "Blog coulisses", description: "Partagez votre processus créatif" },
    ],
    specificFeatures: ["Galeries protégées clients", "Diaporama", "Tarifs prestations", "FAQ"],
    digitalServices: ["site_web", "seo_local", "reservation", "reseaux_sociaux", "ecommerce", "google_ads", "emailing"],
    stats: [
      { label: "Demandes de shooting", value: "+80%" },
      { label: "Ventes tirages", value: "+40%" },
      { label: "Notoriété", value: "+90%" },
    ],
    faqs: [
      { question: "Puis-je créer des galeries privées clients ?", answer: "Oui, chaque client peut avoir un accès protégé par mot de passe pour voir et télécharger ses photos." },
      { question: "La vente de tirages est-elle possible ?", answer: "Absolument, nous intégrons une boutique avec différents formats et finitions." },
    ],
  },
  {
    slug: "vidéaste",
    name: "Vidéaste",
    namePlural: "Vidéastes",
    icon: "Video",
    category: "tech",
    metaTitle: "Site Web Vidéaste | Portfolio Vidéo",
    metaDescription: "Création site portfolio vidéaste. Showreel, réalisations, devis en ligne. Mettez en avant vos productions vidéo.",
    headline: "Vos créations vidéo méritent une scène",
    subheadline: "Un site dynamique qui présente votre showreel et génère des demandes de production.",
    painPoints: [
      "Vidéos dispersées sur YouTube/Vimeo",
      "Pas de portfolio centralisé",
      "Processus de devis long",
      "Concurrence nombreuse",
    ],
    solutions: [
      { title: "Showreel en héros", description: "Votre meilleur travail en plein écran d'accueil" },
      { title: "Projets par catégorie", description: "Corporate, mariage, clip, pub... organisés clairement" },
      { title: "Devis intelligent", description: "Formulaire avec type de projet et budget" },
      { title: "Équipements", description: "Présentez votre matériel professionnel" },
    ],
    specificFeatures: ["Intégration Vimeo/YouTube", "Témoignages clients", "Processus de travail", "Tarifs"],
    digitalServices: ["site_web", "seo_local", "reseaux_sociaux", "google_ads", "crm"],
    stats: [
      { label: "Demandes de projets", value: "+75%" },
      { label: "Qualité des leads", value: "+60%" },
      { label: "Projets corporate", value: "+50%" },
    ],
    faqs: [
      { question: "Comment optimiser le chargement des vidéos ?", answer: "Nous utilisons les lecteurs Vimeo/YouTube optimisés avec lazy loading pour une expérience fluide." },
      { question: "Puis-je montrer mon processus ?", answer: "Oui, une page 'Comment je travaille' rassure les clients sur votre professionnalisme." },
    ],
  },
  {
    slug: "developpeur-freelance",
    name: "Développeur Freelance",
    namePlural: "Développeurs Freelances",
    icon: "Code",
    category: "tech",
    metaTitle: "Site Web Développeur Freelance | Portfolio Dev",
    metaDescription: "Création site portfolio développeur freelance. Projets, technologies, contact. Attirez des missions de développement.",
    headline: "Votre code mérite une vitrine pro",
    subheadline: "Un portfolio technique qui met en avant vos projets et attire des missions.",
    painPoints: [
      "Difficile de montrer du code de façon attractive",
      "Dépendance aux plateformes (Malt, etc.)",
      "Besoin de prouver ses compétences",
      "Tarif journalier difficile à justifier",
    ],
    solutions: [
      { title: "Portfolio projets", description: "Études de cas techniques avec stack utilisée" },
      { title: "Compétences techniques", description: "Technologies maîtrisées avec niveau d'expertise" },
      { title: "Blog tech", description: "Articles techniques pour démontrer votre expertise" },
      { title: "Contact qualifié", description: "Formulaire avec type de projet et budget" },
    ],
    specificFeatures: ["GitHub intégré", "Témoignages clients", "Disponibilités", "TJM indicatif"],
    digitalServices: ["site_web", "seo_local", "google_ads", "reseaux_sociaux", "crm", "emailing"],
    stats: [
      { label: "Demandes de mission", value: "+80%" },
      { label: "TJM négocié", value: "+25%" },
      { label: "Missions directes", value: "+60%" },
    ],
    faqs: [
      { question: "Comment montrer mes projets GitHub ?", answer: "Nous intégrons vos repos GitHub avec statistiques et contributions pour prouver votre activité." },
      { question: "Le blog technique est-il utile ?", answer: "Absolument, il démontre votre expertise et améliore votre référencement sur des termes techniques." },
    ],
  },

  // ============================================
  // AUTRES SERVICES
  // ============================================
  {
    slug: "garage-automobile",
    name: "Garage Automobile",
    namePlural: "Garages Automobiles",
    icon: "Car",
    category: "artisanat",
    metaTitle: "Site Web Garage Automobile | Mécanique & Entretien",
    metaDescription: "Création site internet garage automobile. Prise de RDV en ligne, devis, services. Développez votre garage.",
    headline: "Votre garage visible sur le web",
    subheadline: "Un site pratique pour vos clients avec prise de RDV et demande de devis en ligne.",
    painPoints: [
      "Standard téléphonique saturé",
      "Clients qui ne reviennent pas",
      "Difficile de promouvoir les services",
      "Concurrence des centres auto",
    ],
    solutions: [
      { title: "Prise de RDV en ligne", description: "Vos clients réservent leur créneau 24/7" },
      { title: "Services détaillés", description: "Entretien, réparation, contrôle technique..." },
      { title: "Devis en ligne", description: "Estimation pour les travaux courants" },
      { title: "Programme fidélité", description: "Incitez vos clients à revenir" },
    ],
    specificFeatures: ["Rappels entretien", "Véhicules occasion", "Pièces détachées", "Avis Google"],
    digitalServices: ["site_web", "seo_local", "reservation", "avis_google", "crm", "automation", "emailing", "app_mobile"],
    stats: [
      { label: "RDV en ligne", value: "+60%" },
      { label: "Fidélisation", value: "+40%" },
      { label: "Appels réduits", value: "-50%" },
    ],
    faqs: [
      { question: "Puis-je vendre des véhicules d'occasion ?", answer: "Oui, nous créons une section VO avec fiches détaillées et formulaire de contact." },
      { question: "Les rappels d'entretien sont-ils possibles ?", answer: "Nous pouvons intégrer un système de rappels automatiques par email pour les révisions." },
    ],
  },
  {
    slug: "agence-voyage",
    name: "Agence de Voyage",
    namePlural: "Agences de Voyage",
    icon: "Plane",
    category: "services",
    metaTitle: "Site Web Agence de Voyage | Voyages sur mesure",
    metaDescription: "Création site internet agence de voyage. Destinations, devis voyage, inspiration. Attirez des voyageurs.",
    headline: "Faites rêver vos clients en ligne",
    subheadline: "Un site inspirant qui présente vos destinations et génère des demandes de devis.",
    painPoints: [
      "Concurrence des OTA (Booking, Expedia)",
      "Valeur ajoutée du sur-mesure mal comprise",
      "Besoin d'inspirer les voyageurs",
      "Processus de devis long",
    ],
    solutions: [
      { title: "Pages destinations", description: "Fiches inspirantes par pays/région" },
      { title: "Voyages sur mesure", description: "Formulaire détaillé pour créer le voyage idéal" },
      { title: "Carnet de voyage", description: "Blog avec récits et conseils" },
      { title: "Avis voyageurs", description: "Témoignages de clients satisfaits" },
    ],
    specificFeatures: ["Galerie photos HD", "Vidéos immersives", "Newsletter", "Offres spéciales"],
    digitalServices: ["site_web", "seo_local", "google_ads", "facebook_ads", "reseaux_sociaux", "crm", "emailing", "automation", "chatbot"],
    stats: [
      { label: "Demandes de devis", value: "+70%" },
      { label: "Panier moyen", value: "+35%" },
      { label: "Réservations directes", value: "+50%" },
    ],
    faqs: [
      { question: "Comment concurrencer Booking ?", answer: "En mettant en avant votre expertise, le sur-mesure et l'accompagnement humain que les OTA ne proposent pas." },
      { question: "Le blog voyage est-il utile ?", answer: "Essentiel ! Il attire du trafic SEO et positionne votre agence comme experte." },
    ],
  },
  {
    slug: "wedding-planner",
    name: "Wedding Planner",
    namePlural: "Wedding Planners",
    icon: "Heart",
    category: "services",
    metaTitle: "Site Web Wedding Planner | Organisation Mariage",
    metaDescription: "Création site internet wedding planner. Portfolio mariages, prestations, contact. Attirez des futurs mariés.",
    headline: "Votre talent d'organisation en vitrine",
    subheadline: "Un site romantique qui présente vos réalisations et séduit les futurs mariés.",
    painPoints: [
      "Activité très visuelle, besoin de montrer",
      "Concurrence nombreuse",
      "Clients qui ne comprennent pas le métier",
      "Saisonnalité forte",
    ],
    solutions: [
      { title: "Portfolio mariages", description: "Galeries photos de vos plus beaux mariages" },
      { title: "Formules détaillées", description: "Coordination jour J, organisation complète, à la carte" },
      { title: "Témoignages mariés", description: "Avis et photos des couples accompagnés" },
      { title: "Blog inspiration", description: "Tendances, conseils, idées déco" },
    ],
    specificFeatures: ["Prestataires partenaires", "FAQ mariage", "Contact personnalisé", "Instagram feed"],
    digitalServices: ["site_web", "seo_local", "reseaux_sociaux", "facebook_ads", "google_ads", "crm", "emailing", "avis_google"],
    stats: [
      { label: "Demandes de devis", value: "+65%" },
      { label: "Mariages complets", value: "+40%" },
      { label: "Recommandations", value: "+55%" },
    ],
    faqs: [
      { question: "Les photos sont-elles essentielles ?", answer: "Absolument, c'est votre premier argument. Nous vous conseillons sur la sélection et la mise en valeur." },
      { question: "Comment gérer la saisonnalité ?", answer: "Le site permet de capter des leads toute l'année pour les mariages de l'année suivante." },
    ],
  },
  {
    slug: "demenageur",
    name: "Déménageur",
    namePlural: "Déménageurs",
    icon: "Truck",
    category: "services",
    metaTitle: "Site Web Déménageur | Entreprise Déménagement",
    metaDescription: "Création site internet entreprise déménagement. Devis en ligne, services, zone intervention. Générez des demandes.",
    headline: "Le déménageur de confiance de votre région",
    subheadline: "Un site qui génère des demandes de devis et rassure vos clients.",
    painPoints: [
      "Clients méfiants (arnaques)",
      "Beaucoup de demandes de devis à traiter",
      "Concurrence sur les prix",
      "Réputation difficile à établir",
    ],
    solutions: [
      { title: "Devis en ligne", description: "Calculateur de volume et estimation instantanée" },
      { title: "Services détaillés", description: "Particuliers, entreprises, international..." },
      { title: "Garanties", description: "Assurances et engagements clairement affichés" },
      { title: "Avis clients", description: "Témoignages vérifiés pour rassurer" },
    ],
    specificFeatures: ["Calculateur volume", "Zone intervention", "Cartons et fournitures", "FAQ"],
    digitalServices: ["site_web", "seo_local", "google_ads", "avis_google", "crm", "automation"],
    stats: [
      { label: "Demandes de devis", value: "+80%" },
      { label: "Conversion", value: "+45%" },
      { label: "Confiance", value: "+60%" },
    ],
    faqs: [
      { question: "Le calculateur de volume est-il précis ?", answer: "Il donne une estimation fiable basée sur le type de logement. Le devis final est affiné après visite technique." },
      { question: "Comment rassurer sur les arnaques ?", answer: "Nous mettons en avant vos certifications, assurances et avis vérifiés." },
    ],
  },
]

/**
 * Récupère un secteur par son slug
 */
export function getSectorBySlug(slug: string): Sector | undefined {
  return sectors.find((s) => s.slug === slug)
}

/**
 * Récupère tous les slugs pour generateStaticParams
 */
export function getAllSectorSlugs(): string[] {
  return sectors.map((s) => s.slug)
}

/**
 * Récupère les secteurs par catégorie
 */
export function getSectorsByCategory(category: Sector["category"]): Sector[] {
  return sectors.filter((s) => s.category === category)
}

/**
 * Labels des catégories pour l'affichage
 */
export const categoryLabels: Record<Sector["category"], string> = {
  commerce: "Commerce & Retail",
  services: "Services Professionnels",
  sante: "Santé & Bien-être",
  artisanat: "Artisanat & BTP",
  tech: "Tech & Créatif",
  autre: "Autres Services",
}
